# Generated by Django 2.2.6 on 2020-05-27 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupload',
            name='pdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
