# Generated by Django 2.2.6 on 2020-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPSApp', '0003_pupload_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupload',
            name='ereport',
            field=models.FileField(default='', upload_to='Project/Ereports/'),
            preserve_default=False,
        ),
    ]
