# Generated by Django 2.2.6 on 2020-06-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPSApp', '0006_auto_20200528_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupload',
            old_name='about',
            new_name='gucomments',
        ),
        migrations.RenameField(
            model_name='pupload',
            old_name='pstatus',
            new_name='gustatus',
        ),
        migrations.RenameField(
            model_name='pupload',
            old_name='comments',
            new_name='hocomments',
        ),
        migrations.RemoveField(
            model_name='pupload',
            name='photo_5',
        ),
        migrations.AddField(
            model_name='pupload',
            name='hostatus',
            field=models.CharField(default='Pending', max_length=250),
        ),
        migrations.DeleteModel(
            name='gstatus',
        ),
    ]
