# Generated by Django 2.2.6 on 2020-06-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPSApp', '0008_auto_20200610_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupload',
            name='rating',
            field=models.IntegerField(default='3'),
        ),
    ]
